"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Save, Upload, RefreshCw, Plus } from "lucide-react";
import { sponsorRequest, sponsorWorkspaceRequest as call } from "@/lib/api/sponsor-workspace";
import { listAuthorizedMarkets, listAuthorizedSources, type MarketOption, type SourceOption } from "@/lib/api/content-context";
import { newWizardConfig, resumeWizardConfig, wizardIssues, WIZARD_STEPS, type WizardConfig } from "@/lib/competition/wizard";
import type { DocumentRecord, DraftRecord, Organization } from "@/lib/competition/repository";

export default function SponsorWorkspace() {
  const [organizations, setOrganizations] = useState<Organization[]>([]), [organization, setOrganization] = useState<Organization | null>(null);
  const [markets, setMarkets] = useState<MarketOption[]>([]), [sources, setSources] = useState<SourceOption[]>([]);
  const [drafts, setDrafts] = useState<DraftRecord[]>([]), [saved, setSaved] = useState<DraftRecord | undefined>();
  const [documents, setDocuments] = useState<DocumentRecord[]>([]), [config, setConfig] = useState(newWizardConfig);
  const [retryDocument, setRetryDocument] = useState<DocumentRecord | null>(null);
  const [jobs, setJobs] = useState<Array<{ id: string; status: string; provider: string; model: string; error_code: string | null }>>([]);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [view, setView] = useState("competitions");
  const writable = organization && organization.role !== "sponsor_viewer";
  const manage = organization && ["sponsor_owner", "sponsor_admin", "super_admin"].includes(organization.role);
  async function refresh(sponsor?: string) {
    const rows = await call<Organization[]>("list_organizations"); setOrganizations(rows);
    const id = sponsor ?? rows[0]?.sponsor_id;
    if (id) { setOrganization(await call<Organization>("organization", id)); setDrafts(await call<DraftRecord[]>("list_drafts", id)); }
  }
  async function run(work: () => Promise<void>) { if (busy) return; setBusy(true); setError(""); setNotice(""); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : "SPONSOR_REQUEST_FAILED"); } finally { setBusy(false); } }
  useEffect(() => { let live = true; Promise.all([call<Organization[]>("list_organizations"), listAuthorizedMarkets()]).then(async ([rows, options]) => { if (!live) return; setOrganizations(rows); setMarkets(options); if (rows[0]) { const org = await call<Organization>("organization", rows[0].sponsor_id); const list = await call<DraftRecord[]>("list_drafts", rows[0].sponsor_id); if (live) { setOrganization(org); setDrafts(list); } } }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, []);
  useEffect(() => { let live = true; setSources([]); if (config.scope === "GLOBAL" || config.scope === "LOCAL_MARKET" && config.marketIds.length === 1 || config.scope === "MULTI_MARKET" && config.marketIds.length >= 2) listAuthorizedSources(undefined, { scope: config.scope, markets: config.marketIds }).then(rows => { if (live) setSources(rows); }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, [config.scope, config.marketIds]);
  useEffect(() => { let live = true; setJobs([]); if (organization && saved) call<Array<{ id: string; status: string; provider: string; model: string; error_code: string | null }>>("jobs", organization.sponsor_id, { competition_id: saved.competition_id }).then(rows => { if (live) setJobs(rows); }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, [organization, saved]);
  function set<K extends keyof WizardConfig>(key: K, value: WizardConfig[K]) { setConfig(current => ({ ...current, [key]: value })); }
  async function save() {
    if (!organization) return;
    const result = await call<DraftRecord>("save_draft", organization.sponsor_id, { competition_id: saved?.competition_id ?? null, revision: saved?.revision ?? null, configuration: config });
    setSaved(result); setNotice("Draft saved."); setDrafts(await call<DraftRecord[]>("list_drafts", organization.sponsor_id));
  }
  async function refreshJobs() {
    if (organization && saved) setJobs(await call("jobs", organization.sponsor_id, { competition_id: saved.competition_id }));
  }
  async function submitSource(form: FormData) {
    if (!organization || !saved) return;
    form.set("sponsor", organization.sponsor_id); form.set("competition", saved.competition_id); form.set("market", config.marketIds[0] ?? "");
    if (retryDocument) form.set("document", retryDocument.id);
    try { await sponsorRequest("/api/sponsor/source", form); setRetryDocument(null); setNotice("Source uploaded. Approval pending."); }
    finally { setDocuments(await call("documents", organization.sponsor_id, { competition_id: saved.competition_id })); }
  }
  const text = (key: keyof WizardConfig, label: string, type = "text") => <label>{label}<input type={type} value={String(config[key])} onChange={e => set(key, e.target.value as never)} disabled={busy || !writable}/></label>;
  const numeric = (key: keyof WizardConfig, label: string) => <label>{label}<input type="number" min={0} value={Number(config[key])} onChange={e => set(key, Number(e.target.value) as never)} disabled={busy || !writable}/></label>;
  const select = (key: keyof WizardConfig, label: string, options: string[]) => <label>{label}<select value={String(config[key])} onChange={e => set(key, e.target.value as never)} disabled={busy || !writable}>{options.map(option => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select></label>;
  const toggle = (key: keyof WizardConfig, label: string) => <label><input type="checkbox" checked={Boolean(config[key])} onChange={e => set(key, e.target.checked as never)} disabled={busy || !writable}/>{label}</label>;
  return <>
    <div className="qb-page-head"><h1>Sponsor competitions</h1><select aria-label="Organization" value={organization?.sponsor_id ?? ""} disabled={busy} onChange={e => run(async () => { await refresh(e.target.value); setSaved(undefined); setConfig(newWizardConfig()); setDocuments([]); })}><option value="">Select organization</option>{organizations.map(o => <option key={o.sponsor_id} value={o.sponsor_id}>{o.organization_name}</option>)}</select></div>
    {error && <p role="alert" className="qb-error">{error}</p>}{notice && <p role="status">{notice}</p>}
    <div role="tablist" className="qb-content-filters">{["competitions", "organization"].map(tab => <button role="tab" aria-selected={view === tab} key={tab} onClick={() => setView(tab)}>{tab}</button>)}</div>
    {(!organization || view === "organization") && <section className="qb-content-ops"><h2>{organization?.organization_name ?? "Create organization"}</h2>
      <form key={organization?.sponsor_id ?? "new"} onSubmit={e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { if (organization) await call("edit_organization", organization.sponsor_id, data); else { const market = markets.find(m => m.id === data.market_id); const result = await call<{ sponsor_id: string }>("create_organization", null, { ...data, country_id: market?.country_id }); await refresh(result.sponsor_id); } await refresh(organization?.sponsor_id); setNotice("Organization saved."); }); }}>
        <fieldset disabled={busy || Boolean(organization && !manage)} className="qb-content-filters"><label>Organization name<input name="organization_name" defaultValue={organization?.organization_name} required/></label><label>Organization type<input name="organization_type" defaultValue={organization?.organization_type} required disabled={Boolean(organization)}/></label><label>Contact name<input name="contact_name" defaultValue={organization?.contact_name}/></label><label>Contact email<input name="contact_email" type="email" defaultValue={organization?.contact_email} required/></label><label>Phone<input name="contact_phone" defaultValue={organization?.contact_phone}/></label><label>Website<input name="website" type="url" defaultValue={organization?.website}/></label>{!organization && <label>Market<select name="market_id" required>{markets.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}<button type="submit"><Save size={16}/>Save organization</button></fieldset>
      </form>
      {organization && <><h3>Members</h3>{organization.members?.map(member => <div className="qb-row" key={member.user_id}><span>{member.user_id} · {member.role} · {member.active ? "Active" : "Inactive"}</span>{manage && <button disabled={busy} onClick={() => run(async () => { await call("member", organization.sponsor_id, { ...member, active: !member.active }); await refresh(organization.sponsor_id); })}>{member.active ? "Deactivate" : "Activate"}</button>}</div>)}{manage && <form onSubmit={e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); run(async () => { await call("member", organization.sponsor_id, { ...data, active: true }); await refresh(organization.sponsor_id); }); }}><div className="qb-content-filters"><label>User UUID<input name="user_id" required/></label><label>Role<select name="role">{["sponsor_viewer", "sponsor_editor", "sponsor_admin", "sponsor_owner"].map(role => <option key={role}>{role}</option>)}</select></label><button disabled={busy}><Plus size={16}/>Save member</button></div></form>}</>}
    </section>}
    {organization && view === "competitions" && <section className="qb-content-ops">
      <div className="qb-content-filters"><select aria-label="Draft" value={saved?.competition_id ?? ""} disabled={busy} onChange={e => run(async () => { if (!e.target.value) { setSaved(undefined); setConfig(newWizardConfig()); setDocuments([]); return; } const draft = await call<DraftRecord>("draft", organization.sponsor_id, { competition_id: e.target.value }); setSaved(draft); setConfig(resumeWizardConfig(draft.configuration)); setDocuments(await call<DocumentRecord[]>("documents", organization.sponsor_id, { competition_id: draft.competition_id })); })}><option value="">New competition</option>{drafts.map(d => <option key={d.competition_id} value={d.competition_id}>{String(d.configuration.title)}</option>)}</select><button disabled={busy || !writable || !config.title.trim()} onClick={() => run(save)}><Save size={16}/>Save draft</button></div>
      <nav aria-label="Competition steps" className="qb-content-filters">{WIZARD_STEPS.map((label, i) => <button key={label} aria-current={config.step === i ? "step" : undefined} disabled={busy} onClick={() => set("step", i)}>{i + 1}. {label}</button>)}</nav>
      <h2>{WIZARD_STEPS[config.step]}</h2>
      <div className="qb-content-filters">
        {config.step === 0 && <>{text("title", "Title")}{text("description", "Description")}{text("registrationOpensAt", "Registration opens", "datetime-local")}{text("registrationClosesAt", "Registration closes", "datetime-local")}{text("startsAt", "Starts", "datetime-local")}{text("endsAt", "Ends", "datetime-local")}</>}
        {config.step === 1 && <>{select("audience", "Audience", ["student", "teacher", "public", "employee", "custom"])}{select("access", "Access", ["public", "private", "invite_only"])}{text("grades", "Grades / levels")}{text("institutions", "Institution UUIDs")}{text("minAge", "Minimum age", "number")}{text("maxAge", "Maximum age", "number")}</>}
        {config.step === 2 && <><label>Scope<select value={config.scope} disabled={busy || !writable} onChange={e => { set("scope", e.target.value); set("marketIds", []); set("sourceIds", []); }}>{["LOCAL_MARKET", "MULTI_MARKET", "GLOBAL"].map(scope => <option key={scope}>{scope}</option>)}</select></label>{config.scope !== "GLOBAL" && <fieldset disabled={busy || !writable}><legend>Markets</legend>{markets.map(m => <label key={m.id}><input type={config.scope === "LOCAL_MARKET" ? "radio" : "checkbox"} name="markets" checked={config.marketIds.includes(m.id)} onChange={e => { set("marketIds", config.scope === "LOCAL_MARKET" ? [m.id] : e.target.checked ? [...config.marketIds, m.id] : config.marketIds.filter(id => id !== m.id)); set("sourceIds", []); }}/>{m.name}</label>)}</fieldset>}</>}
        {config.step === 3 && <label>Source mode<select value={config.sourceMode} disabled={busy || !writable} onChange={e => { set("sourceMode", e.target.value); set("sourceIds", []); }}>{["CURRICULUM_ALIGNED", "SPONSOR_SOURCE", "HYBRID"].map(mode => <option key={mode}>{mode}</option>)}</select></label>}
        {config.step === 4 && <fieldset disabled={busy || !writable}><legend>Approved sources</legend>{sources.filter(s => config.sourceMode === "HYBRID" || (config.sourceMode === "SPONSOR_SOURCE" ? s.kind === "SPONSOR_SOURCE" : s.kind !== "SPONSOR_SOURCE")).map(s => <label key={s.id}><input type="checkbox" checked={config.sourceIds.includes(s.id)} onChange={e => set("sourceIds", e.target.checked ? [...config.sourceIds, s.id] : config.sourceIds.filter(id => id !== s.id))}/>{s.title}</label>)}</fieldset>}
        {config.step === 5 && <>{numeric("totalQuestions", "Bank question count")}{numeric("questionsPerAttempt", "Questions per attempt")}{numeric("durationSeconds", "Duration (seconds)")}{numeric("attemptLimit", "Attempt limit")}{numeric("easy", "Easy (%)")}{numeric("medium", "Medium (%)")}{numeric("hard", "Hard (%)")}{toggle("randomizeQuestions", "Randomize questions")}{toggle("randomizeAnswers", "Randomize answers")}{select("scoring", "Scoring", ["points"])}{numeric("negativeMarking", "Negative marking")}{text("passMark", "Pass mark (%)", "number")}{select("tieBreak", "Tie-break", ["score_only", "completion_time"])}{select("answerVisibility", "Answer visibility", ["never", "after_submission", "after_close"])}{select("explanationVisibility", "Explanations", ["never", "after_submission", "after_close"])}{select("leaderboard", "Leaderboard", ["hidden", "during", "after_close"])}{text("topN", "Leaderboard limit", "number")}</>}
        {config.step === 6 && <>{toggle("seniorReviewRequired", "Senior review required")}<span>Human review required</span>{text("provider", "Generation provider")}{text("model", "Generation model")}{text("instructions", "Generation instructions")}</>}
      </div>
      {config.step === 4 && <><form key={retryDocument?.id ?? "new-upload"} onSubmit={e => { e.preventDefault(); if (!saved) { setError("Save the draft before uploading a source."); return; } const form = new FormData(e.currentTarget); run(() => submitSource(form)); }}><div className="qb-content-filters"><label>Source title<input name="title" defaultValue={retryDocument?.title} required readOnly={Boolean(retryDocument)} disabled={busy || !writable}/></label><label>Document<input name="file" type="file" accept=".pdf,.docx,.txt" required disabled={busy || !writable}/></label><label><input name="rightsConfirmed" value="true" type="checkbox" required disabled={busy || !writable}/>Source rights confirmed</label><button disabled={busy || !saved || !writable}><Upload size={16}/>{retryDocument ? "Retry upload" : "Upload"}</button>{retryDocument && <button type="button" disabled={busy} onClick={() => setRetryDocument(null)}>Cancel retry</button>}</div></form>{documents.map(d => <div className="qb-row" key={d.id}><span>{d.title} · {d.ingestion_status} · {d.approval_status}{d.error_code && ` · ${d.error_code}`}</span>{d.error_code === "SOURCE_UPLOAD_FAILED" ? <button disabled={busy || !writable} onClick={() => setRetryDocument(d)}><Upload size={16}/>Retry upload</button> : <button disabled={busy || !writable || !["UPLOADED", "FAILED"].includes(d.ingestion_status)} onClick={() => run(async () => { try { await sponsorRequest("/api/sponsor/source", JSON.stringify({ sponsor: organization.sponsor_id, competition: saved?.competition_id, document: d.id })); } finally { setDocuments(await call<DocumentRecord[]>("documents", organization.sponsor_id, { competition_id: saved?.competition_id })); } })}><RefreshCw size={16}/>{d.ingestion_status === "FAILED" ? "Retry extraction" : "Extract"}</button>}</div>)}</>}
      {config.step >= 7 && <><dl className="qb-content-filters"><div><dt>Competition</dt><dd>{config.title}</dd></div><div><dt>Scope</dt><dd>{config.scope}</dd></div><div><dt>Sources</dt><dd>{config.sourceIds.length}</dd></div><div><dt>Questions / duration</dt><dd>{config.questionsPerAttempt} / {config.durationSeconds}s</dd></div><div><dt>Review</dt><dd>{config.seniorReviewRequired ? "Primary and senior" : "Primary"}</dd></div></dl>{Array.from({ length: 7 }, (_, i) => wizardIssues(config, i)).flat().map((issue, i) => <p key={i} className="qb-error">{issue}</p>)}</>}
      {saved && <section><h3>Generation jobs</h3><button title="Refresh jobs" aria-label="Refresh jobs" disabled={busy} onClick={() => run(refreshJobs)}><RefreshCw size={16}/></button><button disabled={busy || !writable || !config.sourceIds.length || !config.provider.trim() || !config.model.trim()} onClick={() => run(async () => { await call("queue_generation", organization.sponsor_id, { competition_id: saved.competition_id, request_key: crypto.randomUUID(), spec: { scope: config.scope, sourceMode: config.sourceMode, sourceIds: config.sourceIds, marketIds: config.marketIds, count: config.totalQuestions, provider: config.provider, model: config.model, audience: config.audience, grades: config.grades, instructions: config.instructions, difficulty: { easy: config.easy, medium: config.medium, hard: config.hard } } }); await refreshJobs(); setNotice("Generation queued."); })}><Plus size={16}/>Queue generation</button>{jobs.map(job => <div className="qb-row" key={job.id}><span>{job.status} · {job.provider} / {job.model}{job.error_code && ` · ${job.error_code}`}</span>{["QUEUED", "FAILED"].includes(job.status) && <button disabled={busy || !writable} onClick={() => run(async () => { try { if (job.status === "FAILED") await call("retry_generation", organization.sponsor_id, { competition_id: saved.competition_id, job_id: job.id }); await call("execute_generation", organization.sponsor_id, { competition_id: saved.competition_id, job_id: job.id }); } finally { await refreshJobs(); } })}>{job.status === "FAILED" ? "Retry generation" : "Run generation"}</button>}{["QUEUED", "PROCESSING"].includes(job.status) && <button disabled={busy || !writable} onClick={() => run(async () => { await call("cancel_generation", organization.sponsor_id, { competition_id: saved.competition_id, job_id: job.id }); await refreshJobs(); })}>Cancel</button>}</div>)}</section>}
      <div className="qb-content-filters"><button disabled={busy || config.step === 0} onClick={() => set("step", config.step - 1)} title="Previous step"><ArrowLeft size={16}/></button><button disabled={busy || config.step === 8} onClick={() => { const issues = wizardIssues(config, config.step); if (issues.length) setError(issues.join(" ")); else { setError(""); set("step", config.step + 1); } }} title="Next step"><ArrowRight size={16}/></button>{config.step === 8 && <button disabled={busy || !writable || !config.title.trim()} onClick={() => run(save)}><Save size={16}/>Save draft</button>}</div>
    </section>}
  </>;
}
