"use client";
import { useCallback, useEffect, useState } from "react";
import { RefreshCw, X } from "lucide-react";
import { sponsorWorkspaceRequest as call } from "@/lib/api/sponsor-workspace";
type Work = { candidate_id: string; assignment_id: string; competition_id: string; status: string; review_kind: string };
type Detail = { candidate_id: string; assignment: { id: string }; question: { question_text: string; options: string[]; correctAnswer: number; explanation: string; version: number; subject: string; difficulty: string; sourceDocumentId: string; sourceChunkId: string }; validation_errors: string[]; source?: { document_title: string; excerpt: string; page: number | null; chapter: string | null; section: string | null; heading: string | null } };
export default function SponsorCandidateReviews() {
  const [rows, setRows] = useState<Work[]>([]), [detail, setDetail] = useState<Detail | null>(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [note, setNote] = useState(""), [attested, setAttested] = useState(false);
  const load = useCallback(async () => setRows(await call<Work[]>("review_queue")), []);
  useEffect(() => { void load().catch(cause => setError(cause.message)); }, [load]);
  async function perform(work: () => Promise<void>) { if (busy) return; setBusy(true); setError(""); try { await work(); await load(); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  return <section className="qb-content-ops"><div className="qb-page-head"><h2>Competition candidate reviews</h2><button title="Refresh candidate reviews" aria-label="Refresh candidate reviews" disabled={busy} onClick={() => void perform(load)}><RefreshCw size={16}/></button></div>
    {error && <p className="qb-error" role="alert">{error}</p>}
    {rows.map(row => <div className="qb-row" key={row.assignment_id}><span>{row.competition_id} / {row.review_kind} / {row.status}</span><button disabled={busy} onClick={() => void perform(async () => { setDetail(await call<Detail>("review_detail", null, row)); setNote(""); setAttested(false); })}>Open review</button></div>)}
    {detail && <div><div className="qb-page-head"><h3>{detail.question.subject} / {detail.question.difficulty}</h3><button title="Close review" aria-label="Close review" onClick={() => setDetail(null)}><X size={16}/></button></div><p>{detail.question.question_text}</p><ol type="A">{detail.question.options.map(option => <li key={option}>{option}</li>)}</ol><p><strong>Answer:</strong> {detail.question.options[detail.question.correctAnswer]}</p><p><strong>Explanation:</strong> {detail.question.explanation}</p>{detail.source ? <figure><figcaption><strong>Source:</strong> {detail.source.document_title}{[detail.source.page && `page ${detail.source.page}`, detail.source.chapter, detail.source.section, detail.source.heading].filter(Boolean).map(part => ` · ${part}`)}</figcaption><blockquote style={{ whiteSpace: "pre-wrap" }}>{detail.source.excerpt}</blockquote></figure> : <p className="qb-error">Source excerpt unavailable.</p>}<details><summary>Advanced provenance</summary><p><strong>Source document:</strong> {detail.question.sourceDocumentId}</p><p><strong>Source chunk:</strong> {detail.question.sourceChunkId}</p></details><ul>{detail.validation_errors.map(issue => <li key={issue}>{issue}</li>)}</ul>
      <label>Review notes<textarea value={note} minLength={3} maxLength={1000} onChange={e => setNote(e.target.value)}/></label><label><input type="checkbox" checked={attested} onChange={e => setAttested(e.target.checked)}/>I have reviewed the source, question, answer, explanation and validation flags.</label><div className="qb-content-filters">{["approve", "revision", "reject"].map(decision => <button key={decision} disabled={busy || !attested || note.trim().length < 3 || decision === "approve" && detail.validation_errors.length > 0} onClick={() => void perform(async () => { await call("complete_review", null, { candidate_id: detail.candidate_id, assignment_id: detail.assignment.id, version: detail.question.version, decision, note, human_reviewed: attested }); setDetail(null); })}>{decision === "revision" ? "Needs revision" : decision === "approve" ? "Approve" : "Reject"}</button>)}</div>
    </div>}
  </section>;
}
