const messages: Record<string, string> = {
  QB_CONTENT_MARKET_REQUIRED: "Your account needs an assigned content market. Contact your administrator.",
  QB_CONTENT_MARKET_DENIED: "This market is not assigned to your account.",
  QB_CONTENT_CONTEXT_DENIED: "This content context is not available to your account.",
  QB_CONTENT_SOURCE_DENIED: "The selected source is outside your authorized content context or is not approved.",
  QB_CURRICULUM_OUTSIDE_CONTENT_CONTEXT: "This curriculum or objective is outside your selected content context.",
  QB_EXPLICIT_CONTENT_CONTEXT_REQUIRED: "Select an authorized scope and approved sources.",
  QB_EXPLICIT_CURRICULUM_REQUIRED: "Select a curriculum in your current market.",
  QB_SOURCE_MODE_MISMATCH: "The selected sources do not match this source mode.",
  QB_SOURCE_TEXT_REQUIRED: "This source needs a verified extract before generation.",
  QB_COMPETITION_CONTEXT_DENIED: "You cannot configure or access this competition content scope.",
  QB_COMPETITION_CONTEXT_LOCKED: "This competition already has a fixed content scope.",
  QB_COMPETITION_SOURCE_SET_MISMATCH: "Use the competition's fixed source selection for this generation job.",
  QB_MARKET_CONFIGURATION_DENIED: "Super-admin capability is required to configure content markets.",
  QB_APPROVED_SOURCE_IMMUTABLE: "Approved source content cannot be edited. Register a new source version instead.",
  QB_SOURCE_PROVENANCE_REQUIRED: "Confirm source rights, checksum, authority and verified source text before approval.",
  QB_SME_CONFIGURATION_DENIED: "Super-admin capability is required for this configuration.",
  QB_SME_ASSIGNMENT_DENIED: "Content administration capability is required to assign review work.",
  QB_REVIEW_ACCESS_DENIED: "This review is not assigned to you.",
  QB_REVIEW_DOMAIN_DENIED: "Your active subject/domain assignment does not permit this action.",
  QB_ASSIGNED_REVIEW_REQUIRED: "Use the assigned SME review workspace for this question.",
  QB_AMBIGUOUS_COMPENSATION_POLICY: "Multiple compensation policies match. Resolve the conflicting scopes.",
  QB_FINANCE_ACCESS_DENIED: "Finance administration capability is required.",
  QB_INDEPENDENT_PAYOUT_APPROVER_REQUIRED: "A different authorized administrator must approve this batch.",
  QB_BELOW_PAYOUT_THRESHOLD: "The selected earnings are below the configured payout threshold.",
  QB_INELIGIBLE_EARNINGS: "Select payable, unbatched earnings for the same market, currency and period, with verified payment profiles.",
  QB_INVALID_EARNING_TRANSITION: "This earning cannot change state or is already reserved for payout.",
  QB_IMMUTABLE_HISTORY: "Historical review and rate records cannot be edited.",
  QB_SME_PUBLISH_DENIED: "Content or competition publishing capability is required.",
  QB_SENIOR_QA_REQUIRED: "This market requires an independent senior approval before publication.",
  QB_PENDING_SME_REVIEW: "Complete all assigned review work before publication.",
  QB_MARKET_INACTIVE: "Activate the market, country and configured currency before assigning new review work.",
  QB_RATE_LIMITED: "Too many requests. Wait a minute and try again.",
  QB_GRADE_REQUIRED: "Select your learner grade to finish registration.",
  "Invalid login credentials": "The email or password is incorrect.",
  "Email not confirmed": "Verify your email before signing in.",
  AUTH_REQUIRED: "Please sign in again.",
  PROFILE_NOT_FOUND: "Your account is awaiting profile setup. Contact your administrator.",
  ONBOARDING_REQUIRED: "Finish setting up your account to continue.",
  LEARNER_PROFILE_REQUIRED: "Complete your learner profile before registering.", REGISTRATION_CLOSED: "Registration is not open for this competition.",
  MARKET_NOT_ELIGIBLE: "This competition is not open to learners in your country.", AUDIENCE_NOT_ELIGIBLE: "This competition is for a different audience.",
  GRADE_NOT_ELIGIBLE: "This competition is not open to your grade.", INSTITUTION_NOT_ELIGIBLE: "This competition is limited to selected schools.", INVITATION_REQUIRED: "This competition is by invitation only.",
  QB_FACTORY_ACCESS_DENIED: "Content Factory is limited to content administrators.", QB_FACTORY_CAMPAIGN_NOT_FOUND: "That campaign is not available in your markets.",
  QB_FACTORY_SOURCES_REQUIRED: "Select at least one approved curriculum source.", QB_FACTORY_CURRICULUM_NOT_ACTIVE: "Choose an active curriculum with a curriculum authority in this market.",
  QB_FACTORY_SOURCE_CURRICULUM_MISMATCH: "Every source must belong to the selected curriculum.", QB_FACTORY_INVALID_MIX: "Each mix must total exactly 100%.",
  QB_FACTORY_EMPTY_SCOPE: "No active curriculum indicators match the selected levels, grades and subjects.", QB_FACTORY_CAMPAIGN_LOCKED: "This campaign has started; its plan can no longer be edited.",
  QB_FACTORY_PLAN_NOT_READY: "Generate a distribution plan whose total equals the target before starting.", QB_FACTORY_CONFIRMATION_REQUIRED: "Type the campaign name exactly to confirm this large campaign.",
  QB_FACTORY_TOO_MANY_JOBS: "This plan would create too many jobs. Increase the batch size.", QB_FACTORY_INVALID_TRANSITION: "That action is not available for the campaign's current status.",
  QB_FACTORY_NOT_RUNNING: "Generation is not running for this campaign.", QB_FACTORY_SWITCH_MARKET_CONTEXT: "Switch your active market to this campaign's market before running generation.",
  QB_FACTORY_MARKET_IMMUTABLE: "A campaign's market and curriculum cannot change. Create a new campaign.", QB_FACTORY_ALLOCATION_MISMATCH: "One or more plan rows could not be updated. Refresh and try again.",
  QB_FACTORY_CAMPAIGN_MISMATCH: "The campaign does not match the selected market and curriculum.", QB_IMPORT_UNKNOWN_INDICATOR: "The indicator code was not found in this curriculum.",
  QB_WORKFORCE_ACCESS_DENIED: "SME workforce tools are limited to content administrators.", QB_POLICY_OUTSIDE_AUTHORIZATION: "A workload policy must fall within one of the reviewer's authorized domains.",
  QB_POLICY_NOT_FOUND: "That workload policy was not found.", QB_POLICY_REVIEWER_IMMUTABLE: "A policy's reviewer cannot be changed. Create a new policy.", QB_NO_ALLOCATION_POLICIES: "No active campaign-allocation policies exist for this campaign.",
  QB_INVALID_ALLOCATION: "Enter a valid campaign and allocation total.", QB_ASSIGNMENT_NOT_OUTSTANDING: "That review is no longer outstanding.", QB_SME_PROFILE_REQUIRED: "An SME reviewer profile is required.",
  GENERATION_PROVIDER_NOT_CONFIGURED: "No generation provider is configured for this environment.",
  QB_SOURCE_COUNTRY_MISMATCH: "This package's country does not match the target market. Choose the matching country.", QB_SOURCE_MARKET_COUNTRY_MISMATCH: "The source and market countries do not match.",
  QB_SOURCE_CURRICULUM_NOT_IN_MARKET: "That curriculum is not active in this market.", QB_SOURCE_DOCUMENT_MARKET_MISMATCH: "The source document belongs to another market.",
  QB_COUNTRY_PACK_HAS_MULTIPLE_COUNTRIES: "This country pack lists several countries. Import it as a multi-country pack.", QB_PACKAGE_EMPTY: "The package has no source entries.",
  QB_INVALID_PACKAGE_TYPE: "Unsupported package type.", QB_INVALID_PACKAGE: "The package could not be read or is too large.", QB_TARGET_MARKET_NOT_FOUND: "Select a configured target country.",
  QB_IMPORT_CONFIRMATION_REQUIRED: "Confirm the import after reviewing the preview.", QB_PACKAGE_ALREADY_IMPORTED_FOR_MARKET: "This package has already been imported for that market.",
  QB_SOURCE_CLAIM_INVALID: "That fetch claim expired. Run the fetch again.", QB_SOURCE_FETCH_RESULT_INVALID: "The fetched file could not be recorded.", QB_SOURCE_INVALID_TRANSITION: "That action is not available for the source's current status.",
  QB_SOURCE_RIGHTS_ATTESTATION_REQUIRED: "Confirm the source is an official publication QuizBox may use before approving.", QB_SOURCE_HOST_NOT_OFFICIAL: "The URL must be on the authority's official domain.",
  QB_SOURCE_NOT_FOUND: "Source not found.", QB_SOURCE_REGISTRY_DENIED: "The source registry is limited to content and super administrators.", QB_AUTHORITY_NOT_FOUND: "Authority not found.",
  QB_FACTORY_SOURCE_NOT_ACTIVE: "Only active curriculum sources can be used.", QB_FACTORY_SOURCE_SUBJECT_MISMATCH: "A selected source is for a different subject than the campaign.",
  PACKAGE_MANIFEST_NOT_FOUND: "No source manifest was found in the package.", PACKAGE_FORMAT_UNSUPPORTED: "Upload a ZIP, JSON or CSV source package.", PACKAGE_TOO_LARGE: "The package has too many entries.",
  ACCOUNT_SUSPENDED: "This account is suspended. Contact your school or QuizBox support.",
  QB_COUNTRY_NOT_AVAILABLE: "QuizBox is not yet available in this country.",
  QB_INVALID_ONBOARDING_ROLE: "Choose student, teacher or sponsor.",
  QB_INVALID_GRADE: "Choose grades offered in your country.",
  QB_SPONSOR_DETAILS_REQUIRED: "Enter your organization name and contact email.",
  ONBOARDING_ALREADY_COMPLETE: "Your account is already set up.", QB_SCHOOL_REQUIRED: "Enter the school or institution where you teach.",
  QB_MARKET_NOT_AVAILABLE: "That market is not available.", QB_MARKET_UNCHANGED: "That is already your country.",
  QB_OVERRIDE_REASON_REQUIRED: "Enter a reason (at least 5 characters) for assigning outside the class grade.",
  QB_MARKET_CURRICULUM_SOURCE_REQUIRED: "Select an approved curriculum source for every selected market.",
  INVALID_MARKET_TRANSITION: "That market status change is not allowed.", SUPER_ADMIN_REQUIRED: "Only a Super Admin can do this.",
  CURRICULUM_ACTIVATION_REQUIRES_AUTHORITY_AND_APPROVED_SOURCE: "Approve an official source and set the curriculum authority before activating this curriculum.",
  ACTIVE_ADMIN_REQUIRED: "Enter the email of an active QuizBox administrator.", SOURCE_NOT_FOUND: "That source document was not found for this market.",
  CURRENCY_REQUIRED: "Enter the currency name for a new currency.", REQUEST_NOT_PENDING: "This request has already been decided.",
  COMPETITION_CLOSED: "This competition is closed to new registrations and attempts.", COMPETITION_STILL_RUNNING: "Close the competition or wait until it ends before archiving.",
  COMPETITION_NOT_PUBLISHED: "Only a published competition can be closed.", NO_PUBLISHED_VERSION: "This competition has not been published yet.",
  QB_SCHOOL_ADMIN_REQUIRED: "Only a school administrator can do this.", QB_TEACHER_NOT_IN_SCHOOL: "That teacher is not a member of this school.", QB_INVALID_TRANSFER: "Choose an active class in the same school.",
  QB_REPORT_REQUIRES_ATTEMPT: "You can report questions you have answered.", QB_REPORT_REASON_REQUIRED: "Describe the problem in at least five characters.",
  REPORT_NOT_OPEN: "This report has already been resolved.", INVALID_USER_STATUS: "That status change is not allowed.",
  INVALID_CLASS_CODE: "This class code is not valid.",
  CLASS_NOT_ACTIVE: "This class is not open for enrollment.",
  CLASS_CODE_EXPIRED: "This class code has expired.",
  QB_CONTENT_ACCESS_DENIED: "You do not have permission to manage content.", QB_AUTHENTICATION_REQUIRED: "Please sign in again.",
  QB_CONTENT_CONFLICT: "This item changed while you were reviewing it. Reload it before continuing.",
  QB_HUMAN_REVIEW_REQUIRED: "A human editorial review is required before approval.",
  QB_CONTENT_VALIDATION_FAILED: "This question has validation errors. Correct them before continuing.",
  QB_CONTENT_NOT_APPROVED: "Approve this question before publishing it.", QB_REVIEW_NOTE_REQUIRED: "Enter a review note of at least three characters.",
  QB_CONTENT_RATE_LIMIT: "Too many content requests. Wait a minute and try again.", QB_INVALID_BATCH: "The candidate batch is invalid or exceeds 100 questions.",
  QB_ATTEMPT_NOT_ACTIVE: "This attempt has finished. Open its result instead.", QB_ATTEMPT_TIME_EXPIRED: "Your time has expired.",
  QB_ATTEMPT_OWNERSHIP_DENIED: "This attempt is not available to your account.", QB_ASSESSMENT_RECIPIENT_DENIED: "This assessment is not assigned to you.",
  QB_MAX_ATTEMPTS_REACHED: "You have used all attempts for this assessment.", QB_ASSESSMENT_NOT_OPEN: "This assessment is not open yet.", QB_ASSESSMENT_EXPIRED: "This assessment has closed.",
  CLASS_ACCESS_DENIED: "You do not have access to this class.", INSUFFICIENT_APPROVED_QUESTIONS: "There are not enough approved questions for this objective.",
  QB_ASSIGNMENT_CONTEXT_MISMATCH: "This assessment is not available in the selected class.",
  QB_INVALID_GENERATION_SPEC: "The generation specification does not match the curriculum or allowed limits.",
  QB_INVALID_SELECTION: "Select the requested number of distinct approved questions.",
  QB_INSUFFICIENT_APPROVED_QUESTIONS: "There are not enough approved questions for this objective.",
};
// Readable text for a status/blocker code; unknown codes are shown as-is rather than hidden.
export function describeCode(code: string): string { return messages[code] ?? code; }

export function userFacingError(error: unknown): string {
  const message = typeof error === "object" && error !== null && "message" in error ? String(error.message) : String(error);
  return messages[message.split(":")[0]] ?? "The operation could not be completed. Please try again or contact support.";
}
