const messages: Record<string, string> = {
  QB_CONTENT_MARKET_REQUIRED: "Your account needs an assigned content market. Contact your administrator.",
  QB_CONTENT_MARKET_DENIED: "This market is not assigned to your account.",
  QB_CONTENT_CONTEXT_DENIED: "This content context is not available to your account.",
  QB_CONTENT_SOURCE_DENIED: "The selected source is outside your authorized content context or is not approved.",
  QB_CURRICULUM_OUTSIDE_CONTENT_CONTEXT: "This curriculum or objective is outside your selected content context.",
  QB_EXPLICIT_CONTENT_CONTEXT_REQUIRED: "Select an authorized scope and approved sources.",
  QB_EXPLICIT_CURRICULUM_REQUIRED: "Select a curriculum in your current market.",
  QB_SOURCE_MODE_MISMATCH: "The selected sources do not match this source mode.",
  QB_SOURCE_TEXT_REQUIRED: "This source needs a verified extract before generation.",
  QB_COMPETITION_CONTEXT_DENIED: "You cannot configure or access this competition content scope.",
  QB_COMPETITION_CONTEXT_LOCKED: "This competition already has a fixed content scope.",
  QB_COMPETITION_SOURCE_SET_MISMATCH: "Use the competition's fixed source selection for this generation job.",
  QB_MARKET_CONFIGURATION_DENIED: "Super-admin capability is required to configure content markets.",
  QB_APPROVED_SOURCE_IMMUTABLE: "Approved source content cannot be edited. Register a new source version instead.",
  QB_SOURCE_PROVENANCE_REQUIRED: "Confirm source rights, checksum, authority and verified source text before approval.",
  QB_SME_CONFIGURATION_DENIED: "Super-admin capability is required for this configuration.",
  QB_SME_ASSIGNMENT_DENIED: "Content administration capability is required to assign review work.",
  QB_REVIEW_ACCESS_DENIED: "This review is not assigned to you.",
  QB_REVIEW_DOMAIN_DENIED: "Your active subject/domain assignment does not permit this action.",
  QB_ASSIGNED_REVIEW_REQUIRED: "Use the assigned SME review workspace for this question.",
  QB_AMBIGUOUS_COMPENSATION_POLICY: "Multiple compensation policies match. Resolve the conflicting scopes.",
  QB_FINANCE_ACCESS_DENIED: "Finance administration capability is required.",
  QB_INDEPENDENT_PAYOUT_APPROVER_REQUIRED: "A different authorized administrator must approve this batch.",
  QB_BELOW_PAYOUT_THRESHOLD: "The selected earnings are below the configured payout threshold.",
  QB_INELIGIBLE_EARNINGS: "Select payable, unbatched earnings for the same market, currency and period, with verified payment profiles.",
  QB_INVALID_EARNING_TRANSITION: "This earning cannot change state or is already reserved for payout.",
  QB_IMMUTABLE_HISTORY: "Historical review and rate records cannot be edited.",
  QB_SME_PUBLISH_DENIED: "Content or competition publishing capability is required.",
  QB_SENIOR_QA_REQUIRED: "This market requires an independent senior approval before publication.",
  QB_PENDING_SME_REVIEW: "Complete all assigned review work before publication.",
  QB_MARKET_INACTIVE: "Activate the market, country and configured currency before assigning new review work.",
  QB_RATE_LIMITED: "Too many requests. Wait a minute and try again.",
  QB_GRADE_REQUIRED: "Select your learner grade to finish registration.",
  "Invalid login credentials": "The email or password is incorrect.",
  "Email not confirmed": "Verify your email before signing in.",
  AUTH_REQUIRED: "Please sign in again.",
  PROFILE_NOT_FOUND: "Your account is awaiting profile setup. Contact your administrator.",
  INVALID_CLASS_CODE: "This class code is not valid.",
  CLASS_NOT_ACTIVE: "This class is not open for enrollment.",
  CLASS_CODE_EXPIRED: "This class code has expired.",
  QB_CONTENT_ACCESS_DENIED: "You do not have permission to manage content.", QB_AUTHENTICATION_REQUIRED: "Please sign in again.",
  QB_CONTENT_CONFLICT: "This item changed while you were reviewing it. Reload it before continuing.",
  QB_HUMAN_REVIEW_REQUIRED: "A human editorial review is required before approval.",
  QB_CONTENT_VALIDATION_FAILED: "This question has validation errors. Correct them before continuing.",
  QB_CONTENT_NOT_APPROVED: "Approve this question before publishing it.", QB_REVIEW_NOTE_REQUIRED: "Enter a review note of at least three characters.",
  QB_CONTENT_RATE_LIMIT: "Too many content requests. Wait a minute and try again.", QB_INVALID_BATCH: "The candidate batch is invalid or exceeds 100 questions.",
  QB_ATTEMPT_NOT_ACTIVE: "This attempt has finished. Open its result instead.", QB_ATTEMPT_TIME_EXPIRED: "Your time has expired.",
  QB_ATTEMPT_OWNERSHIP_DENIED: "This attempt is not available to your account.", QB_ASSESSMENT_RECIPIENT_DENIED: "This assessment is not assigned to you.",
  QB_MAX_ATTEMPTS_REACHED: "You have used all attempts for this assessment.", QB_ASSESSMENT_NOT_OPEN: "This assessment is not open yet.", QB_ASSESSMENT_EXPIRED: "This assessment has closed.",
  CLASS_ACCESS_DENIED: "You do not have access to this class.", INSUFFICIENT_APPROVED_QUESTIONS: "There are not enough approved questions for this objective.",
  QB_ASSIGNMENT_CONTEXT_MISMATCH: "This assessment is not available in the selected class.",
  QB_INVALID_GENERATION_SPEC: "The generation specification does not match the curriculum or allowed limits.",
  QB_INVALID_SELECTION: "Select the requested number of distinct approved questions.",
  QB_INSUFFICIENT_APPROVED_QUESTIONS: "There are not enough approved questions for this objective.",
};
export function userFacingError(error: unknown): string {
  const message = typeof error === "object" && error !== null && "message" in error ? String(error.message) : String(error);
  return messages[message.split(":")[0]] ?? "The operation could not be completed. Please try again or contact support.";
}
