import { type Candidate, type CurriculumNode, type GenerationSpec } from "./contract";

type Draft = [question: string, correct: string, distractors: [string, string, string], explanation: string];
export const WAVE_ONE_SOURCE_VERSION = "wave-one-original-review-v1";
export const WAVE_ONE_OBJECTIVES = [
  { subject: "Computing", code: "B10.2.4.1.1", objective: "Perform data filtering, sorting, validation", page: 92 },
  { subject: "Computing", code: "B10.2.4.1.3", objective: "Demonstrate the use of data tables, pivot tables, charts and pivot charts.", page: 93 },
  { subject: "Computing", code: "B10.3.3.1.2", objective: "Demonstrate how to protect data using alphanumeric credentials and biometrics.", page: 96 },
  { subject: "Mathematics", code: "B10.1.3.1.1", objective: "Review fractions and solve problems involving basic operations on fractions.", page: 239 },
  { subject: "Mathematics", code: "B10.1.3.1.2", objective: "Add, subtract, multiply and divide fractions using the BODMAS rule to solve problems.", page: 240 },
  { subject: "Mathematics", code: "B10.1.3.1.3", objective: "Review word problems involving basic operations on fractions.", page: 241 },
  { subject: "Science", code: "B10.1.2.1.1", objective: "Discuss specialised cells and how they are formed in dicotyledonous plants and humans.", page: 170 },
  { subject: "Science", code: "B10.1.2.1.2", objective: "Examine the functions of epidermal cells, guard cells, cambium and xylem in dicotyledonous plants.", page: 171 },
  { subject: "Science", code: "B10.1.2.1.3", objective: "Examine the functions of nerve cells, blood cells, muscle cells and sperm cells in humans.", page: 172 },
] as const;

// Original editorial drafts, not copied exam items, fixtures, or academically approved content.
const drafts: Draft[][] = [
  [
    ["A spreadsheet has one learner per row and columns for name, class and score. What is one learner's complete row called?", "A record", ["A field", "A formula", "A worksheet title"], "A record contains the related fields for one entity. The name, class and score columns are fields."],
    ["Which spreadsheet feature restricts entries in a Class column to SHS1A, SHS1B or SHS1C?", "A data-validation list", ["A font colour setting", "A page margin setting", "A chart legend"], "A validation list supplies permitted entries and can reject entries outside that list."],
    ["A teacher filters a score table to show scores of at least 70. What happens to the other records?", "They are hidden by the filter but remain in the table.", ["They are permanently deleted from the table.", "Their scores are automatically changed to 70.", "They are moved into new worksheets automatically."], "Filtering changes which records are displayed; it does not delete the records that fail the condition."],
    ["A name table has columns for surname, first name and score. How should it be sorted alphabetically by surname without mixing learners' scores?", "Sort the entire table using the Surname column as the sort key.", ["Sort only the surname cells and leave other columns unchanged.", "Sort only the Score column from largest to smallest.", "Sort the column headings and leave the data unchanged."], "Sorting complete records preserves the relationship between each learner's name and score. Sorting a single column independently can break that relationship."],
    ["A score table must accept only whole-number scores from 0 to 100 and display only SHS1B learners from highest score to lowest. Which sequence meets all three requirements?", "Validate scores as whole numbers from 0 to 100, filter Class to SHS1B, then sort complete records by Score descending.", ["Validate scores as any text, filter Class to SHS1B, then sort by Score descending.", "Validate scores from 0 to 100, filter Class to SHS1B, then sort only score cells independently.", "Validate scores from 0 to 100, filter Class to SHS1A, then sort complete records by Score ascending."], "Validation controls permitted values, filtering selects the intended class, and a descending whole-record sort preserves identities while ordering scores."],
  ],
  [
    ["What is the main purpose of a pivot table in a spreadsheet?", "To summarise records by selected categories and calculations", ["To encrypt every record with a password", "To convert every cell into a picture", "To replace the spreadsheet with a word-processing file"], "Pivot tables group and summarise data, for example by counting learners or adding quantities in each category."],
    ["A table lists one learner per row and records each learner's house. Which pivot-table arrangement counts learners in each house?", "House in Rows and Count of learner ID in Values", ["Learner ID in Rows and Sum of House in Values", "House in Values and no row category", "Count of learner ID in Rows and House as the chart title"], "House supplies the grouping category; counting non-empty learner IDs gives the number of learners in each group."],
    ["A pivot table uses Count of learner ID to summarise this list: Red house, Red house, Blue house, Green house, Blue house. What count should Blue house show?", "2", ["1", "3", "5"], "There are two Blue-house records. Count measures the number of matching learner records, not the total number of houses."],
    ["A pivot table summarises quantities sold by product. Which chart is most suitable for comparing the total quantities of four products?", "A column chart with one column per product", ["A line chart whose horizontal axis lists learner IDs", "A scatter chart without product labels", "A chart showing only the names of the four products"], "A column chart makes category totals easy to compare. Product names label the categories and quantities determine column heights."],
    ["A sales pivot table shows Sum of Quantity by Product. A learner changes Values to Count of Quantity. Why do the numbers change?", "The table now counts sales records with a quantity instead of adding the quantities sold.", ["Count and Sum always give identical values for every dataset.", "Changing the calculation deletes the underlying sales records.", "Count of Quantity automatically calculates the average selling price."], "Sum adds numeric quantities; Count counts non-empty quantity entries. Several items sold in one record contribute their full quantity to Sum but only one record to Count."],
  ],
  [
    ["Which method uses a biological characteristic to authenticate a user?", "Fingerprint recognition", ["Typing a username", "Entering a password", "Entering a recovery code"], "A fingerprint is a biometric characteristic. A username identifies an account, while passwords and recovery codes are knowledge-based secrets."],
    ["Why should a password be kept private even when a username is publicly known?", "The password is a secret used to prove the account holder's identity.", ["A username always encrypts the password automatically.", "Knowing a username alone prevents anyone from trying to log in.", "A public username makes sharing a password safe."], "The username identifies the account; the password helps authenticate its holder. Disclosing the password enables another person to impersonate the holder."],
    ["A learner learns that a school-portal password has been disclosed. What is the best immediate response?", "Change it to a unique secret and end other sessions where the portal supports this.", ["Share the disclosed password with classmates for confirmation.", "Change only the account's display name and keep the password.", "Use the same disclosed password on a second website."], "Changing the disclosed secret removes its future usefulness for sign-in. Ending other sessions helps limit access through already authenticated sessions."],
    ["A school tablet supports a passphrase and fingerprint authentication. Which action best protects the learner's account when leaving a shared classroom?", "Lock the tablet and keep the passphrase private.", ["Leave the tablet unlocked because the fingerprint sensor is present.", "Write the passphrase on the tablet so the next user can unlock it.", "Disable the screen lock after enrolling a fingerprint."], "Authentication protects access only when access is actually locked. An unlocked session can be used without supplying either credential."],
    ["A school uses facial recognition for tablet access, but a learner's face is not recognised after an injury. Which recovery arrangement best preserves security and access?", "An authorised identity check followed by a private alternative authentication method", ["Automatic unrestricted access whenever recognition fails", "A shared class password printed beside every tablet", "Permanent removal of every screen lock for all learners"], "An authorised recovery process provides an alternative when biometrics fail without making every account accessible to unauthorised users."],
  ],
  [
    ["What is 3/4 + 1/8 in simplest form?", "7/8", ["4/12", "1/2", "5/8"], "Write 3/4 as 6/8, then add 1/8 to obtain 7/8."],
    ["What is 5/6 - 1/4 in simplest form?", "7/12", ["4/2", "1/3", "11/12"], "The common denominator is 12: 5/6 = 10/12 and 1/4 = 3/12. Their difference is 7/12."],
    ["What is 2/3 multiplied by 9/10 in simplest form?", "3/5", ["11/13", "2/5", "5/3"], "Multiplying numerators and denominators gives 18/30, which simplifies to 3/5."],
    ["What is 7/8 divided by 7/16?", "2", ["1/2", "49/128", "7/24"], "Multiply 7/8 by the reciprocal 16/7. Cancelling 7 and simplifying 16/8 gives 2."],
    ["A learner says 2/5 + 1/3 = 3/8 by adding both numerators and denominators. Which correction is valid?", "Use denominator 15: 6/15 + 5/15 = 11/15.", ["Keep denominator 8 and change only the numerator to 11.", "Multiply the fractions to get 2/15 instead of adding them.", "Subtract the denominators to get 3/2."], "Addition requires equal-sized fractional parts. Equivalent fractions with denominator 15 can be added; adding denominators does not preserve the sizes of the parts."],
  ],
  [
    ["Evaluate 1/2 + (1/3 multiplied by 3/4).", "3/4", ["5/8", "1/4", "7/12"], "Multiply first: 1/3 multiplied by 3/4 = 1/4. Then 1/2 + 1/4 = 3/4."],
    ["Evaluate (3/4 - 1/2) divided by 1/8.", "2", ["1/32", "1/4", "6"], "The brackets give 1/4. Dividing 1/4 by 1/8 gives 2."],
    ["Evaluate 5/6 - (1/3 divided by 2/3).", "1/3", ["11/18", "3/4", "1/2"], "Division is performed before subtraction: 1/3 divided by 2/3 = 1/2. Then 5/6 - 1/2 = 2/6 = 1/3."],
    ["Evaluate (2/3 + 1/6) multiplied by 3/5.", "1/2", ["23/30", "1/10", "5/6"], "First calculate the brackets: 2/3 + 1/6 = 5/6. Then 5/6 multiplied by 3/5 = 1/2."],
    ["Evaluate 3/4 divided by 1/2 multiplied by 2/3, carrying out division and multiplication from left to right.", "1", ["9/4", "1/4", "3/2"], "Multiplication and division have equal precedence. From left to right, 3/4 divided by 1/2 = 3/2, then 3/2 multiplied by 2/3 = 1."],
  ],
  [
    ["Ama uses 2/5 metre of ribbon and then 1/4 metre. How much ribbon does she use altogether?", "13/20 metre", ["3/9 metre", "3/20 metre", "7/20 metre"], "Use twentieths: 2/5 = 8/20 and 1/4 = 5/20. The total is 13/20 metre."],
    ["A jug contains 3/4 litre of water. After 1/3 litre is poured out, how much remains?", "5/12 litre", ["2/1 litres", "1/12 litre", "13/12 litres"], "Subtract the amount poured out: 3/4 - 1/3 = 9/12 - 4/12 = 5/12 litre."],
    ["A club has 36 members. Two thirds of them attend a meeting. How many members attend?", "24", ["12", "18", "54"], "One third of 36 is 12, so two thirds is 2 multiplied by 12 = 24 members."],
    ["A container holds 2 1/4 litres of juice. How many full 3/8-litre cups can be filled without spillage?", "6", ["3", "8", "27/32"], "Convert 2 1/4 to 9/4. Divide by 3/8: 9/4 multiplied by 8/3 = 6 full cups."],
    ["A shop has 24 kilograms of rice. It sells 3/8 of the original stock in the morning and 1/4 of the original stock in the afternoon. How many kilograms remain?", "9 kilograms", ["6 kilograms", "11 1/4 kilograms", "15 kilograms"], "The total sold is 3/8 + 1/4 = 5/8 of the original stock, leaving 3/8. Three eighths of 24 kilograms is 9 kilograms. Both sales refer to the original stock."],
  ],
  [
    ["What makes a cell specialised?", "It has features suited to a particular function.", ["It must perform every function of the organism equally.", "It must be visible without a microscope.", "It must have exactly the same shape as every other cell."], "Specialisation links a cell's structure and activity to a particular role in the organism."],
    ["What is the name of the process in which an unspecialised cell develops features for a particular role?", "Differentiation", ["Evaporation", "Pollination", "Condensation"], "Differentiation produces specialised cell features and functions; the other processes do not describe cell specialisation."],
    ["A root-hair cell develops a long extension of its surface. How does this feature support its role?", "It increases surface area for absorbing water and mineral ions.", ["It allows the cell to carry oxygen through human blood.", "It allows the cell to contract and move bones.", "It allows the cell to transmit nerve impulses."], "The extension increases contact with the soil solution, supporting absorption. Oxygen transport, muscle contraction and nerve signalling are different specialised roles."],
    ["Why can a plant's specialised cells look different although they belong to the same plant?", "Different roles require different structural adaptations.", ["Every different cell shape must come from a different species.", "Specialised plant cells all have identical roles.", "Cell shape is unrelated to the work done by the cell."], "Plant cells can differentiate into structures adapted for protection, transport or absorption. Their different shapes need not indicate different species."],
    ["During development, two cells with the same inherited genetic information become a nerve cell and a muscle cell. Which explanation best accounts for their different specialised functions?", "Different sets of genes are active, producing different cell structures and proteins.", ["Each cell must lose all its genetic information before specialising.", "Both cells must become identical because their genetic information is the same.", "The nerve cell must change into a plant cell to acquire a different function."], "Differentiation involves differences in gene activity. These differences can produce specialised structures and proteins without requiring different inherited genomes."],
  ],
  [
    ["Which specialised plant cells regulate the opening and closing of stomata?", "Guard cells", ["Root-hair cells", "Xylem vessel cells", "Cambium cells"], "A pair of guard cells surrounds a stoma and controls the pore opening, affecting gas exchange and water loss."],
    ["What is the main transport role of xylem in a plant?", "Moving water and dissolved mineral ions from the roots through the plant", ["Carrying nerve impulses between the leaves and roots", "Producing sperm cells for human reproduction", "Transporting oxygen in human blood"], "Xylem transports water and mineral ions absorbed by roots to other parts of the plant."],
    ["Which specialised tissue produces new xylem and phloem cells as a dicotyledonous stem grows thicker?", "Vascular cambium", ["The stomatal pore", "The leaf cuticle", "A mature xylem vessel lumen"], "Dividing vascular cambium cells produce secondary xylem and phloem, contributing to the increase in stem thickness."],
    ["A leaf has an outer layer of tightly packed epidermal cells. Which function does this arrangement mainly support?", "Protecting underlying tissues", ["Contracting to pull the leaf along the ground", "Carrying electrical impulses to a human brain", "Forming red blood cells"], "The epidermis forms a protective covering over underlying plant tissues. The other options describe functions that this layer does not perform."],
    ["A plant's stomata remain wide open during a hot, dry afternoon because its guard cells cannot close them. What is the most likely direct effect?", "Greater water loss through the stomata", ["Complete prevention of water loss from the leaf", "Conversion of xylem into red blood cells", "An immediate end to all mineral absorption by root hairs"], "Open stomata permit more water vapour to leave the leaf. Guard-cell closure normally helps reduce this loss when water is scarce."],
  ],
  [
    ["Which specialised human cells primarily carry oxygen from the lungs to body tissues?", "Red blood cells", ["Nerve cells", "Muscle cells", "Sperm cells"], "Red blood cells contain haemoglobin, which binds oxygen for transport in the blood."],
    ["Which specialised human cell transmits electrical signals between parts of the nervous system?", "A nerve cell", ["A red blood cell", "A sperm cell", "A muscle cell"], "Nerve cells conduct impulses for communication in the nervous system. The other cells have different specialised roles."],
    ["How does the flagellum of a sperm cell support its function?", "It helps the sperm move towards an egg cell.", ["It pumps oxygen through the bloodstream.", "It forms a protective plant epidermis.", "It contracts to move the person's arm."], "The flagellum propels the sperm, helping it reach an egg for fertilisation."],
    ["A muscle cell has many mitochondria. Why is this useful during repeated contraction?", "Mitochondria help release energy required for contraction.", ["Mitochondria replace all contractile proteins with cell walls.", "Mitochondria turn the muscle cell into a guard cell.", "Mitochondria carry oxygen outside the cell as red blood cells do."], "Contraction requires energy. Mitochondria supply energy through aerobic respiration, supporting the work of the contractile structures."],
    ["A nerve cell has a long axon, while a red blood cell contains haemoglobin. What does this comparison best demonstrate?", "Different structures support signalling in the nerve cell and oxygen transport in the red blood cell.", ["Both structures enable the cells to perform exactly the same primary function.", "The axon stores oxygen while haemoglobin conducts nerve impulses.", "The presence of haemoglobin means a red blood cell is a plant cell."], "An axon conducts signals along a nerve cell; haemoglobin binds oxygen in red blood cells. Structure and function are related to each cell's specialised role."],
  ],
];

export function waveOneBatch(node: CurriculumNode, source: { file: string; sha256: string }) {
  const index = WAVE_ONE_OBJECTIVES.findIndex((r) => r.subject === node.subject_code && r.code === node.code);
  if (index < 0 || !node.is_active || node.canonical_grade_code !== "SHS1") throw new Error("WAVE_MAPPING_MISMATCH");
  const objective = WAVE_ONE_OBJECTIVES[index];
  const candidates = drafts[index].map(([question, answer, distractors, explanation], i): Candidate => {
    const correctIndex = (index * 5 + i) % 4;
    const options = [...distractors]; options.splice(correctIndex, 0, answer);
    return { external_question_id: `WAVE1:${node.subject_code}:${node.code}:${i + 1}:v1`, curriculum_node_id: node.id,
      question_text: question, answer_type: "SINGLE_CHOICE", option_a: options[0], option_b: options[1], option_c: options[2], option_d: options[3],
      correct_answer: "ABCD"[correctIndex], explanation, difficulty_label: i < 2 ? "easy" : i < 4 ? "medium" : "hard",
      cognitive_level: i < 2 ? "Understand" : i < 4 ? "Apply" : "Analyze", marks: 1, estimated_time_seconds: i < 2 ? 45 : i < 4 ? 75 : 120,
      source_type: "AI_GENERATED", tags: ["EDITORIAL_WAVE_1", "AI_ASSISTED_ORIGINAL", "HUMAN_REVIEW_REQUIRED", `curriculum-source:${source.file}`, `curriculum-sha256:${source.sha256}`, `curriculum-page:${objective.page}`, `objective-summary:${objective.objective}`] };
  });
  const spec: GenerationSpec = { indicatorId: node.id, indicatorCode: node.code, indicatorTitle: node.title, curriculumId: node.curriculum_id,
    educationLevel: node.education_level ?? "SHS", grade: node.canonical_grade_code!, subject: node.subject_code!, difficulty: "medium", cognitiveLevel: "Apply",
    answerType: "SINGLE_CHOICE", count: candidates.length, language: "English", marks: 1, expectedSeconds: 75,
    provenance: { source: "AI_GENERATED", provider: "Codex-assisted-original-composition", sourceVersion: WAVE_ONE_SOURCE_VERSION } };
  return { spec, candidates, objective, curriculumSource: source, approval: "HUMAN_REVIEW_REQUIRED" };
}
