import { beforeAll,describe,it,expect } from "vitest";
import { createClient,type SupabaseClient } from "@supabase/supabase-js";
import { acceptanceAccount } from "./acceptance";
describe.skipIf(process.env.QB_LIVE_ACCEPTANCE!=="1")("final live authorization gates",()=>{
 let student:SupabaseClient,seller:SupabaseClient,sponsor:SupabaseClient,teacher:SupabaseClient,admin:SupabaseClient,anon:SupabaseClient;
 beforeAll(async()=>{process.loadEnvFile(".env.local");const make=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});student=make();seller=make();sponsor=make();teacher=make();admin=make();anon=make();for(const [client,role] of [[student,"student"],[seller,"seller"],[sponsor,"sponsor"],[teacher,"teacher"],[admin,"admin"]] as const){expect((await client.auth.signInWithPassword(acceptanceAccount(role))).error).toBeNull();}});
 const invalid="00000000-0000-0000-0000-000000000001";
 it.each(["qb_attach_competition_sponsor","qb_finalize_competition_leaderboard","qb_record_competition_result"])("anonymous and ordinary roles cannot mutate %s",async(name)=>{const args=name==="qb_attach_competition_sponsor"?{p_competition_id:invalid,p_sponsor_id:invalid}:name==="qb_record_competition_result"?{p_competition_id:invalid,p_entity_type:"STUDENT",p_entity_id:invalid,p_score:0}:{p_competition_id:invalid};for(const client of [anon,student,sponsor,seller])expect((await client.rpc(name,args)).error).not.toBeNull();});
 it("seller retains authorized own-entity update",async()=>{const own=await seller.from("marketplace_sellers").select("id,display_name").single();expect(own.error).toBeNull();const updated=await seller.from("marketplace_sellers").update({display_name:own.data!.display_name}).eq("id",own.data!.id).select("id");expect(updated.error).toBeNull();expect(updated.data).toEqual([{id:own.data!.id}]);});
 it("student cannot mutate the actual acceptance seller",async()=>{const own=await seller.from("marketplace_sellers").select("id,display_name").single();expect(own.error).toBeNull();const update=await student.from("marketplace_sellers").update({display_name:own.data!.display_name}).eq("id",own.data!.id).select("id");expect(update.error!==null||update.data?.length===0).toBe(true);});
 it("sponsor profile is readable only in its authorized context",async()=>{const own=await sponsor.from("sponsor_profiles").select("id,organization_name").single();expect(own.error).toBeNull();const other=await student.from("sponsor_profiles").select("id").eq("id",own.data!.id);expect(other.error!==null||other.data?.length===0).toBe(true);});
 it("ordinary student cannot insert a marketplace seller for another user",async()=>{const owner=await seller.auth.getUser();const r=await student.from("marketplace_sellers").insert({seller_type:"USER",seller_entity_id:owner.data.user!.id,display_name:"DEV_ACCEPTANCE_FIXTURE denied seller"});expect(r.error).not.toBeNull();});
 it("production review excludes all fixture namespaces",async()=>{const r=await admin.rpc("qb_content_queue",{p_filters:{source:"production",status:"review"},p_page:1,p_limit:25});expect(r.error).toBeNull();expect(r.data.total).toBeGreaterThanOrEqual(45);expect(r.data.rows.every((q:any)=>!["DEV_ACCEPTANCE_FIXTURE","DEV_FACTORY_PILOT"].includes(q.source_type))).toBe(true);});
 it.each([0,-1,100001])("learner pagination rejects page %s",async(p_page)=>{const r=await teacher.rpc("qb_indicator_learners_page",{p_class_id:"8ef5da7d-887b-4972-b708-fe698df7336e",p_node_id:"00eb0221-eb96-4002-b2cd-5c5f273cd51f",p_page,p_limit:25});expect(r.error).not.toBeNull();});
 it("learner drill-down is stable, bounded and owner-authorized",async()=>{const args={p_class_id:"8ef5da7d-887b-4972-b708-fe698df7336e",p_node_id:"00eb0221-eb96-4002-b2cd-5c5f273cd51f",p_page:1,p_limit:1};const a=await teacher.rpc("qb_indicator_learners_page",args),b=await teacher.rpc("qb_indicator_learners_page",args);expect(a.error).toBeNull();expect(a.data.rows.length).toBeLessThanOrEqual(1);expect(a.data).toEqual(b.data);expect((await student.rpc("qb_indicator_learners_page",args)).error).not.toBeNull();});
});
